kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: kinnairdclan/mattermost-team-edition
    tags:
      - latest
      - 'v6.3.8_custom'
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_access_token
